/* Generated By:JavaCC: Do not edit this line. AlParseConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMICO = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int EQUA = 14;
  /** RegularExpression Id. */
  int LCB = 15;
  /** RegularExpression Id. */
  int RCB = 16;
  /** RegularExpression Id. */
  int LBRAC = 17;
  /** RegularExpression Id. */
  int RBRAC = 18;
  /** RegularExpression Id. */
  int PLUS_SIGN = 19;
  /** RegularExpression Id. */
  int MINUS_SIGN = 20;
  /** RegularExpression Id. */
  int TILDA = 21;
  /** RegularExpression Id. */
  int LOG_OR = 22;
  /** RegularExpression Id. */
  int LOG_AND = 23;
  /** RegularExpression Id. */
  int EQUATE = 24;
  /** RegularExpression Id. */
  int NOT_EQUA = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int LTOET = 27;
  /** RegularExpression Id. */
  int GT = 28;
  /** RegularExpression Id. */
  int GTOET = 29;
  /** RegularExpression Id. */
  int VAR = 30;
  /** RegularExpression Id. */
  int CONST = 31;
  /** RegularExpression Id. */
  int RETURN = 32;
  /** RegularExpression Id. */
  int INTEGER = 33;
  /** RegularExpression Id. */
  int BOOLEAN = 34;
  /** RegularExpression Id. */
  int VOID = 35;
  /** RegularExpression Id. */
  int MAIN = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int ELSE = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int WHILE = 41;
  /** RegularExpression Id. */
  int SCIP = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int ID = 45;
  /** RegularExpression Id. */
  int INT = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"skip\"",
    "<DIGIT>",
    "<LETTER>",
    "<ID>",
    "<INT>",
  };

}
